Incoporate compile from source Aptos binaries

diff --git a/src/docker/compose.e2e.yml b/src/docker/compose.e2e.yml
--- a/src/docker/compose.e2e.yml
+++ b/src/docker/compose.e2e.yml
@@ -7,37 +7,96 @@ services:
       dockerfile: src/docker/aptos-builder/Dockerfile
     image: aptos-builder
 
-  chain:
-    build:
-      context: ../../
-      dockerfile: src/docker/chain/Dockerfile
-    depends_on:
-      - aptos-builder
-    image: chain
-    ports:
-      - 8080:8080
-      - 8081:8081
-
   diesel:
     build:
-      context: ../../
-      dockerfile: src/docker/database/Dockerfile
       args:
         - DATABASE_URL=postgres://econia:econia@docker_default/econia
+      context: ../../
+      dockerfile: src/docker/database/Dockerfile
     depends_on:
       - postgres
 
+  # Modeled off of Aptos Core validator-testnet Docker compose.
+  faucet:
+    build:
+      context: ../../
+      dockerfile: src/docker/faucet/Dockerfile
+    command: >
+      /bin/bash -c "
+        for i in {1..10}; do
+          if [[ ! -s /opt/aptos/var/mint.key ]]; then
+            echo 'Validator has not populated mint.key yet. Is it running?'
+            sleep 1
+          else
+            sleep 1
+            /usr/local/bin/aptos-faucet-service \\
+              run-simple \\
+              --key-file-path /opt/aptos/var/mint.key \\
+              --chain-id TESTING \\
+              --node-url http://172.16.1.10:8080
+            echo 'Faucet failed to run likely due to the Validator still starting. Will try again.'
+          fi
+        done
+        exit 1
+      "
+    depends_on:
+      - validator
+    image: faucet
+    #networks:
+      #shared:
+        #ipv4_address:  172.16.1.11
+    ports:
+      - "8081:8081"
+    volumes:
+      - type: volume
+        source: aptos-shared
+        target: /opt/aptos/var
+
   postgres:
-    image: postgres:14-alpine
-    restart: always
     environment:
       - POSTGRES_USER=econia
       - POSTGRES_PASSWORD=econia
+    image: postgres:14-alpine
     ports:
       - 5432:5432
+    restart: always
     volumes:
       - db:/var/lib/postgresql/data
+
+  # Modeled off of Aptos Core validator-testnet Docker compose.
+  validator:
+    build:
+      context: ../../
+      dockerfile: src/docker/validator/Dockerfile
+    command: [
+      "/usr/local/bin/aptos-node",
+      "--test",
+      "--test-dir",
+      "/opt/aptos/var/",
+      "--test-config-override",
+      "/opt/aptos/config.yaml"
+    ]
+    depends_on:
+      - aptos-builder
+    expose:
+      - 9101
+    image: validator
+    #networks:
+      #shared:
+        #ipv4_address:  172.16.1.10
+    ports:
+      - "8080:8080" # REST API.
+      - "50051:50051" # Indexer GRPC.
+    volumes:
+      - type: volume
+        source: aptos-shared
+        target: /opt/aptos/var
+      - type: bind
+        source: validator/e2e_config.yaml
+        target: /opt/aptos/config.yaml
 
 volumes:
   db:
     driver: local
+  aptos-shared:
+    name: aptos-shared
